AWSTemplateFormatVersion: '2010-09-09'
Description: 'fiap-trip

  Rest API to manage a Data Lake of trip links

  '
Globals:
  Function:
    MemorySize: 512
    Timeout: 20
Outputs:
  CreateTripRecordFunction:
    Description: CreateTripRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripRecordFunction
      - Arn
  GetTripsByCityFunction:
    Description: GetTripsByCity Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripsByCityFunction
      - Arn
  GetTripsByCountryFunction:
    Description: GetTripsByCountry Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripsByCountryFunction
      - Arn
  GetTripsRecordsByPeriodFunction:
    Description: GetTripsRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripsRecordsByPeriodFunction
      - Arn
Resources:
  CreateTripRecordFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        CreateStudyRecord:
          Properties:
            Method: post
            Path: /trip
          Type: Api
      Handler: br.com.iwe.handler.CreateTripRecord::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripsByCityFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripsByCity:
          Properties:
           Path: /trips/{country}/city
           Method: get
           RequestParameters:
            - method.request.querystring.city
          Type: Api
      Handler: br.com.iwe.handler.GetTripsByCity::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripsByCountryFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripsByCountry:
          Properties:
           Path: /trips/{country}
           Method: get
           RequestParameters:
            - method.request.path.country
          Type: Api
      Handler: br.com.iwe.handler.GetTripsByCountry::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripsByPeriodFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripsByPeriod:
          Properties:
           Path: /trips
           Method: get
           RequestParameters:
            - method.request.querystring.start
            - method.request.querystring.end
          Type: Api
      Handler: br.com.iwe.handler.GetTripsByPeriod::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
